### ISSUE TITLE
ICAPServer OVA ulimit needs to be increased

### ISSUE THREAD

**Issue by shashanksinha89** [k8-proxy/GW-proxy#237] opened 2020-12-09 12:05 UTC

**Comment by mahnouman** [comment] 2020-12-09 17:12
Duplicate of https://github.com/k8-proxy/GW-proxy/issues/222

**Closed by mahnouman** 2020-12-09 17:12 UTC

**Comment by uzfarid** [comment] 2020-12-09 18:01
@mahnouman  those are not duplicates. #222 is referencing to this ticket
